### ISSUE TITLE
[Feature Request] Allow destination with custom domain (GHES)

### ISSUE THREAD

**Issue by oldking139** [repo-sync/github-sync#114]
When I using [Github enterprise server](https://docs.github.com/en/enterprise-server@3.10/admin/overview/about-github-enterprise-server) with our custom domain, we can simply fetch repo **from** github.com, but when pushing to internal repo, the error log shows:
```
fatal: repository 'https://github.com/<org-name>/<repo-name>/' not found
```
I create this actions file in our **internal repo** to sync from github.com.

```
name: Sync from Github.com

on:
    schedule:
    - cron:  "*/15 * * * *"
    workflow_dispatch:

jobs:
    repo-sync:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "${{secrets.SOURCE_REPO}}"
          source_branch: "*"
          destination_branch: "*"
          github_token: ${{ secrets.PAT }}
          sync_tags: "true"
```

As we using custom domain rather than github.com, I think it is good to have an option to change the prefix or the full repository name before we set the "destination branch", for example, add a `destination_repo` option in actions.
