### ISSUE TITLE
fatal: repository not found

### ISSUE THREAD

**Issue by zeke** [repo-sync/github-sync#18]
Hi @wei. I'm hitting a snag setting up a workflow and I'm hoping you can help diagnose.

Here's the error I'm seeing:

![Screen Shot 2020-03-25 at 8 48 48 PM](https://user-images.githubusercontent.com/2289/77608317-19067180-6eda-11ea-90aa-1a35ad9eea8e.png)

I've tried setting the `SOURCE_REPO` secret in two formats:

- `https://<access_token>@github.com/github/help-docs.git`
- `https://zeke:<access_token>@github.com/github/help-docs.git`

but either way I'm getting this output:

```
UPSTREAM_REPO=***
BRANCHES=master:repo-sync
remote: Repository not found.
fatal: repository 'https://github.com/github/help-docs.git/' not found
```

Here's the workflow file:

```yml
name: Repo Sync

on:
  schedule: 
  - cron: "0 * * * *" # every hour, on the hour

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      env:
        GITHUB_TOKEN: ${{ secrets.ZEKE_PAT_WITH_REPO_AND_WORKFLOW_SCOPE_FOR_REPO_SYNC }}
      with:
        source_repo: ${{ secrets.SOURCE_REPO }}
        source_branch: master
        destination_branch: repo-sync
        github_token: ${{ secrets.ZEKE_PAT_WITH_REPO_AND_WORKFLOW_SCOPE_FOR_REPO_SYNC }}
    - uses: repo-sync/pull-request@v2
      name: Create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.ZEKE_PAT_WITH_REPO_AND_WORKFLOW_SCOPE_FOR_REPO_SYNC }}
      with:
        source_branch: repo-sync
        destination_branch: master
        github_token: ${{ secrets.ZEKE_PAT_WITH_REPO_AND_WORKFLOW_SCOPE_FOR_REPO_SYNC }}
```

The `ZEKE_PAT_WITH_REPO_AND_WORKFLOW_SCOPE_FOR_REPO_SYNC` secret, as its ridiculously long name suggests, is a token with repo and workflow scope created with my @zeke account, so it should have access to that repository.

Any ideas?

**Comment by wei** [comment]
I don't see anything apparent. Could you try running these two lines in a fresh environment?
https://github.com/repo-sync/github-sync/blob/520596e97177727db1f2a1de14f4ded905624066/github-sync.sh#L27-L28

**Comment by spoorendonk** [comment]
I have the exact same issue.
I am syncing a private repo in an organization

**Comment by wei** [comment]
Looks like GitHub actions automatically set extraheader basic authorization header in the `.git/config` This is overwriting the PAT provided in the url. 
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/repo-sync/private-destination-repo
	fetch = +refs/heads/*:refs/remotes/origin/*
[gc]
	auto = 0
[http "https://github.com/"]
	extraheader = AUTHORIZATION: basic ***
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

Looking for a fix now.

**Comment by wei** [comment]
@zeke @spoorendonk You can try the fix with `repo-sync/github-sync@fix-private-source-with-pat`

**Comment by zeke** [comment]
Thanks @wei! I will give this a try soon and get back to you.

**Comment by spoorendonk** [comment]
Works in my case. Thanks @wei

**Comment by wei** [comment]
@zeke Merging for now, let me know if you see any issues.

**Comment by zeke** [comment]
Hey sorry for the slowness following up. This fix worked for us! 🎉

**Comment by wei** [comment]
No worries!

@spoorendonk please use @v2 as the hofix branch may be deleted anytime.

**Comment by Lemmingh** [comment]
> Looks like GitHub actions automatically set extraheader basic authorization header

This is introduced by [Checkout V2](https://github.com/marketplace/actions/checkout), and is controlled by its `persist-credentials` option.

**Comment by connecteev** [comment]
Hi @wei 
I went to https://github.com/settings/tokens and created a new Personal Access token with **all** scopes selected.

I then went to a **new** server and ran:
git clone https://connecteev:${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}@github.com/xxxxxxxxxxx/yyyyyyyyyy.git
and was able to clone the repo successfully


I then changed my yml file to:
```
name: Repo Sync # from https://github.com/repo-sync/github-sync
on:
  push:
  schedule: 
  - cron: "*/3 * * * *" # every 3 mins (for now)

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: https://connecteev:${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}@github.com/xxxxxxxxxxx/yyyyyyyyyy.git
        source_branch: '*'
        destination_branch: '*'
        github_token: ${{ secrets.GITHUB_TOKEN }}

```

but I am still seeing the same error in the output of github actions run:
```
UPSTREAM_REPO=https://github.com/xxxxxxxxxxx/yyyyyyyyyy.git
BRANCHES=*:*
remote: Repository not found.
fatal: repository 'https://github.com/xxxxxxxxxxx/yyyyyyyyyy.git/' not found
```

**Comment by wei** [comment]
@connecteev thanks for testing out the action. I just realized the `@v2` tag is not pointing to the latest version `@2.1.0`. It has been fixed, so if you run the action again it will not show the `Repository not found.` error anymore. However,

1. because you are running this action on the repo's default branch, the (push to destination repo step) will fail because GITHUB_TOKEN does not have access to overwritting GitHub action files, you could use `github_token: ${{ secrets. MY_PERSONAL_ACCESS_TOKEN }}` instead of `secrets.GITHUB_TOKEN` then the sync & push should succeed.
1. however, once it does succeed, your workflow file will be overwritten & deleted and will no longer run.

Therefore, I recommend using a third repo as a taskrunner with [wei/git-sync](https://github.com/wei/git-sync) action. It is very similar to this one but provides more flexibility allowing for any Git source and destination.

Cheers!

**Comment by connecteev** [comment]
Hi @wei thank you for the quick fix! And for the explanation. I was able to get it to work with your help 👍 
Your points 1 and 2 above are spot on, however I did not need to use the wei/git-sync action (I'm sure it's useful, but I simply created another '_syncing' branch with my workflow file - of course this assumes that my source repo is never going to have a '_syncing' branch with the same name).

Here is my final yml file (both for my future reference and for someone else that may encounter the same issue).
```
name: Repo Sync # from https://github.com/repo-sync/github-sync

on:
  push:
  schedule:
  - cron: "*/3 * * * *" # 3 mins (for now)

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        # MY_PERSONAL_ACCESS_TOKEN_FROM_GITHUB_SETTINGS is set to my personal access token from https://github.com/settings/tokens)
        source_repo: https://connecteev:${{ secrets.MY_PERSONAL_ACCESS_TOKEN_FROM_GITHUB_SETTINGS }}@github.com/xxxxxxxx/yyyyyyyyyy.git
        source_branch: '*'
        destination_branch: '*'
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN_FROM_GITHUB_SETTINGS }}

```

Really appreciate your help!
