### ISSUE TITLE
refusing to allow an integration to create or update .github/workflows/*.yml

### ISSUE THREAD

**Issue by zeke** [repo-sync/github-sync#8]
We have a long-running PR that was updating just fine until it hit this:

```
 * [new branch]            using-saml-broken-link -> tmp_upstream/using-saml-broken-link
 * [new tag]               legacy_content_removal_20170503 -> legacy_content_removal_20170503
 * [new tag]               pre-nanoc            -> pre-nanoc
origin	https://zeke:***@github.com/docs/docs (fetch)
origin	https://zeke:***@github.com/docs/docs (push)
tmp_upstream	*** (fetch)
tmp_upstream	*** (push)
To https://github.com/docs/docs
 ! [remote rejected]         tmp_upstream/master -> sync (refusing to allow an integration to create or update .github/workflows/check-all-english-links.yml)
error: failed to push some refs to 'https://zeke:***@github.com/docs/docs'
```

This is the part of our Workflow where this fails:

```yml
- uses: repo-sync/github-sync@v2
  name: Sync repo to branch
  with:
    source_repo: ${{ secrets.SOURCE_REPO }}
    source_branch: "master"
    destination_branch: sync
    github_token: ${{ secrets.GITHUB_TOKEN }}
```
